PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS articles;

CREATE TABLE IF NOT EXISTS articles (
  id INTEGER UNIQUE NOT NULL PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
)

-- CREATE INDEX idx_articles_title ON articles (title);

DROP TABLE IF EXISTS jobs;

CREATE TABLE IF NOT EXISTS jobs (
  id INTEGER UNIQUE NOT NULL PRIMARY KEY AUTOINCREMENT,
  job_status TEXT NOT NULL,
  image_url TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (article_id) REFERENCES articles(id)
);

